Competed prep-html-skeleton Noah Khayat
NaeemK1188/javascript-prep-1124-code-solutions pull request #4
Opened 2024-12-03 08:31 UTC by NaeemK1188

![prep-html-skeleton](https://github.com/user-attachments/assets/b5efb9e3-cc72-4908-9adf-3e76e8fe2eb2)

2024-12-03 08:44 UTC, NaeemK1188 commented
![Screenshot (357)](https://github.com/user-attachments/assets/0a1a4ff5-74ab-41c3-87ca-44e489fff22c)

2024-12-03 23:14 UTC, shawnkost requested changes
You need to answer the quiz questions as well Noah!

2024-12-03 23:14 UTC, shawnkost commented on prep-html-skeleton/prep-html-skeleton-exercise-quiz-notes.md
> +
Don't forget to answer the quiz questions!

2024-12-04 01:07 UTC, NaeemK1188 commented
![Screenshot (358)](https://github.com/user-attachments/assets/3e48d2b5-d65b-4c5b-9056-41f8a92e344e)

these are the missing quiz answers attached in the image

2024-12-04 01:55 UTC, shawnkost approved these changes
👍🏻

2024-12-04 01:59 UTC, merged